import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "College Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
        <html lang="en">
      <body
      > 
      {/* <Header/> */}
        {children}
      </body>
    </html>
     </ClerkProvider>
 
  );
}
